[MediaStreamTrack-transfer-to-worker-cross-origin.https.html]
  prefs: [media.mediastreamtrack.transferable.enabled:true]
  # MediaStreamTrackProcessor is not implemented.
  [Frames of same-origin media reach a worker]
    expected: FAIL

  [Frames of cross-origin media are black in a worker]
    expected: FAIL

  [Frames of cross-origin media loaded with CORS reach a worker]
    expected: FAIL

  [Frames turn black in a worker when the media switches to a cross-origin source]
    expected: FAIL
